// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRlrLXD6JKkj6hZ2sKrQYe6mqxohHw0wY',
    appId: '1:798700016778:web:b136cc6c888385a0dc8973',
    messagingSenderId: '798700016778',
    projectId: 'testflutter-2cd38',
    authDomain: 'testflutter-2cd38.firebaseapp.com',
    storageBucket: 'testflutter-2cd38.appspot.com',
    measurementId: 'G-JC95F9VSCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDisZ1jCxcBrrjrnWZzJrxhTlkyVykR5LM',
    appId: '1:798700016778:android:de8dd8db818f2856dc8973',
    messagingSenderId: '798700016778',
    projectId: 'testflutter-2cd38',
    storageBucket: 'testflutter-2cd38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUGmTVQTPjUL0keiyh7SatxWHpnaG8PxI',
    appId: '1:798700016778:ios:eb2b5abefb7ccaf2dc8973',
    messagingSenderId: '798700016778',
    projectId: 'testflutter-2cd38',
    storageBucket: 'testflutter-2cd38.appspot.com',
    iosBundleId: 'com.example.lasttry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUGmTVQTPjUL0keiyh7SatxWHpnaG8PxI',
    appId: '1:798700016778:ios:eb2b5abefb7ccaf2dc8973',
    messagingSenderId: '798700016778',
    projectId: 'testflutter-2cd38',
    storageBucket: 'testflutter-2cd38.appspot.com',
    iosBundleId: 'com.example.lasttry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRlrLXD6JKkj6hZ2sKrQYe6mqxohHw0wY',
    appId: '1:798700016778:web:e07525a7edd0f2ebdc8973',
    messagingSenderId: '798700016778',
    projectId: 'testflutter-2cd38',
    authDomain: 'testflutter-2cd38.firebaseapp.com',
    storageBucket: 'testflutter-2cd38.appspot.com',
    measurementId: 'G-0S6ZZ5TW5V',
  );

}